definitions:
  models.DepositRequest:
    properties:
      amount:
        type: number
      currency:
        type: string
      payment_method:
        type: string
      user_id:
        type: integer
      uuid:
        type: string
    required:
    - amount
    - currency
    - user_id
    type: object
  psp.CancelRequest:
    properties:
      transactionID:
        type: string
    type: object
  psp.PayInResponse:
    properties:
      redirectUrl:
        type: string
      transactionID:
        type: string
    type: object
info:
  contact: {}
paths:
  /payments/cancel:
    post:
      consumes:
      - application/json
      description: Handles the cancellation callback from the Payment Service Provider
        (PSP) when a deposit is cancelled.
      parameters:
      - description: PSP API Key
        in: header
        name: X-PSP-API-Key
        required: true
        type: string
      - description: Cancellation callback from PSP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/psp.CancelRequest'
      responses:
        "200":
          description: Deposit cancelled successfully
          schema:
            type: string
        "401":
          description: Unauthorized - Invalid API key
          schema:
            type: object
      summary: Cancel a Deposit Transaction
      tags:
      - payments
  /payments/confirm:
    post:
      consumes:
      - application/json
      description: Handles the confirmation callback from the Payment Service Provider
        (PSP) after a successful deposit.
      parameters:
      - description: PSP API Key
        in: header
        name: X-PSP-API-Key
        required: true
        type: string
      - description: Confirmation callback from PSP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/psp.PayInResponse'
      responses:
        "200":
          description: Deposit confirmed successfully
          schema:
            type: string
        "401":
          description: Unauthorized - Invalid API key
          schema:
            type: object
      summary: Confirm a Deposit Transaction
      tags:
      - payments
  /payments/deposit:
    post:
      consumes:
      - application/json
      description: Creates a new PENDING transaction and redirects the user to the
        Payment Service Provider (PSP) for payment completion.
      parameters:
      - description: Deposit initiation details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DepositRequest'
      responses:
        "302":
          description: Redirect to PSP payment page
          schema:
            type: object
      summary: Initiate a Deposit Transaction
      tags:
      - payments
swagger: "2.0"
